import type { ThirdSpace, UniversityLandmark } from './supabase';

// 🏛️ The 12 Manila University Campus Anchor Landmarks
export const MANILA_UNIVERSITIES: UniversityLandmark[] = [
  { id: 'uni-upm', name: 'University of the Philippines Manila', shortCode: 'UPM', lat: 14.5794, lng: 120.9882, city: 'Manila' },
  { id: 'uni-ust', name: 'University of Santo Tomas', shortCode: 'UST', lat: 14.6091, lng: 120.9893, city: 'Manila' },
  { id: 'uni-dlsu', name: 'De La Salle University Manila', shortCode: 'DLSU', lat: 14.5648, lng: 120.9932, city: 'Manila' },
  { id: 'uni-feu', name: 'Far Eastern University Manila', shortCode: 'FEU', lat: 14.6041, lng: 120.9866, city: 'Manila' },
  { id: 'uni-ue', name: 'University of the East Manila', shortCode: 'UE', lat: 14.6025, lng: 120.9889, city: 'Manila' },
  { id: 'uni-nu', name: 'National University Manila', shortCode: 'NU Manila', lat: 14.6043, lng: 120.9942, city: 'Manila' },
  { id: 'uni-adu', name: 'Adamson University', shortCode: 'AdU', lat: 14.5872, lng: 120.9858, city: 'Manila' },
  { id: 'uni-pup', name: 'Polytechnic University of the Philippines', shortCode: 'PUP', lat: 14.5979, lng: 121.0108, city: 'Manila' },
  { id: 'uni-plm', name: 'Pamantasan ng Lungsod ng Maynila', shortCode: 'PLM', lat: 14.5867, lng: 120.9762, city: 'Manila' },
  { id: 'uni-csb', name: 'De La Salle-College of Saint Benilde', shortCode: 'DLSU-CSB', lat: 14.5628, lng: 120.9950, city: 'Manila' },
  { id: 'uni-mapua', name: 'Mapúa University Intramuros', shortCode: 'Mapúa', lat: 14.5905, lng: 120.9761, city: 'Manila' },
  { id: 'uni-cghc', name: 'Chinese General Hospital Colleges', shortCode: 'CGHC', lat: 14.6225, lng: 120.9877, city: 'Manila' },
];

// ☕ Third Space Spots around Manila Universities
export const MOCK_SPOTS: ThirdSpace[] = [
  {
    id: 'spot-1',
    university_id: 'uni-upm',
    title: 'UP Manila Learning Resource Center & Library',
    category: 'library',
    description: 'Quiet public study area for UPM students with aircon, research databases, and study desks.',
    address: 'Pedro Gil St, Ermita, Manila',
    lat: 14.5794,
    lng: 120.9882,
    price_range: 'Free',
    has_wifi: true,
    has_outlets: true,
    is_24_7: false,
    is_free: true,
    needs_student_id: true,
    comp_shop_reg_required: false,
    indoor_outdoor: 'indoor',
    seat_capacity: 'Spacious',
    commute_info: {
      lrt: 'LRT-1 Pedro Gil Station (3 min walk)',
      jeep: 'Faura - Pedro Gil route',
    },
    peak_hours: '1 PM - 5 PM',
    panorama_url: 'https://pannellum.org/images/alma.jpg',
    cover_image_url: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'spot-2',
    university_id: 'uni-upm',
    title: 'Pedro Gil Budget Kainan & Carinderia Hub',
    category: 'kainan',
    description: 'Popular student budget food spot with affordable rice meals below ₱80 (UPM PENGE MORE KAINAN PLSZ!).',
    address: 'Pedro Gil St corner Taft Ave, Manila',
    lat: 14.5788,
    lng: 120.9890,
    price_range: '₱',
    has_wifi: false,
    has_outlets: false,
    is_24_7: true,
    is_free: false,
    needs_student_id: false,
    comp_shop_reg_required: false,
    indoor_outdoor: 'both',
    seat_capacity: 'Moderate',
    commute_info: {
      lrt: 'LRT-1 Pedro Gil Station (1 min walk)',
      jeep: 'Taft Ave jeepneys',
    },
    peak_hours: '11 AM - 2 PM',
    cover_image_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'spot-3',
    university_id: 'uni-ust',
    title: 'Dapitan 24/7 Study Cafe',
    category: 'cafe',
    description: 'Cozy 24-hour study cafe near UST Dapitan gate with strong Wi-Fi and power outlets at every desk.',
    address: 'Dapitan St, Sampaloc, Manila',
    lat: 14.6102,
    lng: 120.9898,
    price_range: '₱₱',
    has_wifi: true,
    has_outlets: true,
    is_24_7: true,
    is_free: false,
    needs_student_id: false,
    comp_shop_reg_required: false,
    indoor_outdoor: 'indoor',
    seat_capacity: 'Moderate',
    commute_info: {
      jeep: 'Dapitan - Quiapo jeepney',
      bus: 'SM Fairview - PITX bus',
    },
    peak_hours: '6 PM - 2 AM',
    panorama_url: 'https://pannellum.org/images/cerro-toco.jpg',
    cover_image_url: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'spot-4',
    university_id: 'uni-dlsu',
    title: 'Taft Co-Working & Study Lounge',
    category: 'coworking',
    description: 'Modern study hub opposite DLSU campus featuring high-speed fiber internet and free brewed coffee.',
    address: 'Taft Ave, Malate, Manila',
    lat: 14.5652,
    lng: 120.9938,
    price_range: '₱₱',
    has_wifi: true,
    has_outlets: true,
    is_24_7: true,
    is_free: false,
    needs_student_id: false,
    comp_shop_reg_required: false,
    indoor_outdoor: 'indoor',
    seat_capacity: 'Spacious',
    commute_info: {
      lrt: 'LRT-1 Vito Cruz Station (2 min walk)',
    },
    peak_hours: '2 PM - 10 PM',
    panorama_url: 'https://pannellum.org/images/boulder.jpg',
    cover_image_url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'spot-5',
    university_id: 'uni-plm',
    title: 'Intramuros Public Reading Room & Garden',
    category: 'park',
    description: 'Serene open-air garden space with shade and stone benches inside historic Intramuros near PLM & Mapúa.',
    address: 'General Luna St, Intramuros, Manila',
    lat: 14.5894,
    lng: 120.9752,
    price_range: 'Free',
    has_wifi: false,
    has_outlets: false,
    is_24_7: false,
    is_free: true,
    needs_student_id: false,
    comp_shop_reg_required: false,
    indoor_outdoor: 'outdoor',
    seat_capacity: 'Spacious',
    commute_info: {
      lrt: 'LRT-1 Central Terminal Station (10 min walk)',
      jeep: 'Mabini / Pier 15 jeepneys',
    },
    peak_hours: '4 PM - 7 PM',
    cover_image_url: 'https://images.unsplash.com/photo-1519331379826-f10be5486c6f?auto=format&fit=crop&w=800&q=80',
  },
];
