import type { ThirdSpace, UniversityLandmark } from './supabase';

// Import Local Asset Images
import imgPahuway from '../assets/Images/Cafe/Pahuway Coffee.jpg';
import imgCoffeeProject from '../assets/Images/Cafe/Coffee Project co-lab.jpg';
import imgBreaktimeBrew from '../assets/Images/Cafe/Breaktime Brew.jpg';

import imgNatlib from '../assets/Images/Libraries/Natlib.jpg';
import imgManilaLibTaft from '../assets/Images/Libraries/Manila Lib Taft.jpg';
import imgManilaLibMain from '../assets/Images/Libraries/Manila Lib Lacson_Tayuman.jpg';
import imgJplLib from '../assets/Images/Libraries/Jose P Laurel Lib.jpg';
import imgMagsaysayLib from '../assets/Images/Libraries/Ramon Magsaysay.webp';
import imgCentroTurismoLib from '../assets/Images/Libraries/Centro de Turismo Library.jpg';

import imgRizalPark from '../assets/Images/Park/Rizal Park.jpg';
import imgArrocerosPark from '../assets/Images/Park/Arroceros Forest Park.jpg';
import imgPacoPark from '../assets/Images/Park/Paco Park.jpg';

import imgHomeRoom from '../assets/Images/Study Hub/HomeRoom.jpg';
import img933Coworking from '../assets/Images/Study Hub/933 coworking cafe.jpg';
import imgHashLab from '../assets/Images/Study Hub/Hash Lab budget study cafe.jpg';
import imgCloudscape from '../assets/Images/Study Hub/Cloudscape study hub.jpeg';

// 🏛️ The 12 Manila University Campus Anchor Landmarks (Exact Pinpoint GPS)
export const MANILA_UNIVERSITIES: UniversityLandmark[] = [
  { id: 'uni-upm', name: 'University of the Philippines Manila', shortCode: 'UPM', lat: 14.57913, lng: 120.98342, city: 'Manila' },
  { id: 'uni-ust', name: 'University of Santo Tomas', shortCode: 'UST', lat: 14.61028, lng: 120.98917, city: 'Manila' },
  { id: 'uni-dlsu', name: 'De La Salle University Manila', shortCode: 'DLSU', lat: 14.5649, lng: 120.9931, city: 'Manila' },
  { id: 'uni-feu', name: 'Far Eastern University Manila', shortCode: 'FEU', lat: 14.6038, lng: 120.9855, city: 'Manila' },
  { id: 'uni-ue', name: 'University of the East Manila', shortCode: 'UE', lat: 14.6019, lng: 120.9895, city: 'Manila' },
  { id: 'uni-nu', name: 'National University Manila', shortCode: 'NU Manila', lat: 14.60417, lng: 120.99417, city: 'Manila' },
  { id: 'uni-adu', name: 'Adamson University', shortCode: 'AdU', lat: 14.5850, lng: 120.9850, city: 'Manila' },
  { id: 'uni-pup', name: 'Polytechnic University of the Philippines', shortCode: 'PUP', lat: 14.59722, lng: 121.01083, city: 'Manila' },
  { id: 'uni-plm', name: 'Pamantasan ng Lungsod ng Maynila', shortCode: 'PLM', lat: 14.5870, lng: 120.9760, city: 'Manila' },
  { id: 'uni-csb', name: 'De La Salle-College of Saint Benilde', shortCode: 'DLSU-CSB', lat: 14.5582, lng: 120.9904, city: 'Manila' },
  { id: 'uni-mapua', name: 'Mapúa University Intramuros', shortCode: 'Mapúa', lat: 14.5907, lng: 120.9779, city: 'Manila' },
  { id: 'uni-cghc', name: 'Chinese General Hospital Colleges', shortCode: 'CGHC', lat: 14.62525, lng: 120.98794, city: 'Manila' },
];

// ☕ 16 Authentic Manila Student Third Spaces (Exact Pinpoint GPS Table)
export const MOCK_SPOTS: ThirdSpace[] = [
  // --- CAFES ---
  {
    id: 'spot-pahuway',
    university_id: 'uni-upm',
    title: 'Pahuway Coffee - UPM Taft',
    category: 'cafe',
    description: 'A cozy, quiet local hideout located at Joshua Center across PGH UPM Taft. Known for its peaceful study ambiance, strong Wi-Fi, and accessible power sockets at almost every table.',
    address: 'Joshua Center, Taft Ave, Ermita, Manila',
    lat: 14.5795,
    lng: 120.9865,
    price_range: '₱₱',
    has_wifi: true,
    has_outlets: true,
    is_24_7: false,
    is_free: false,
    needs_student_id: false,
    comp_shop_reg_required: false,
    indoor_outdoor: 'indoor',
    seat_capacity: 'Moderate',
    commute_info: {
      lrt: 'LRT-1 Pedro Gil Station (2 min walk)',
      jeep: 'Taft Ave jeepneys',
    },
    peak_hours: '2 PM - 7 PM',
    cover_image_url: imgPahuway,
  },
  {
    id: 'spot-coffee-project-colab',
    university_id: 'uni-dlsu',
    title: 'Coffee Project Co-Lab - Taft DLSU',
    category: 'cafe',
    description: 'An ultra-conducive, unique co-working coffee space located at Vista Taft Residences near DLSU and Benilde with high ceilings, quiet zones, and fast Wi-Fi.',
    address: 'Vista Taft Residences, Taft Ave, Malate, Manila',
    lat: 14.5635,
    lng: 120.9925,
    price_range: '₱₱',
    has_wifi: true,
    has_outlets: true,
    is_24_7: true,
    is_free: false,
    needs_student_id: false,
    comp_shop_reg_required: false,
    indoor_outdoor: 'indoor',
    seat_capacity: 'Spacious',
    commute_info: {
      lrt: 'LRT-1 Vito Cruz Station (3 min walk)',
    },
    peak_hours: '1 PM - 10 PM',
    cover_image_url: imgCoffeeProject,
  },
  {
    id: 'spot-breaktime-brew',
    university_id: 'uni-mapua',
    title: 'Breaktime Brew - Intramuros',
    category: 'cafe',
    description: 'A charming local cafe along Clemente Jose St inside historic Intramuros near Mapúa and PLM. Perfect for quiet study breaks away from noisy mainstream coffee chains.',
    address: 'Clemente Jose St, Intramuros, Manila',
    lat: 14.5895,
    lng: 120.9755,
    price_range: '₱',
    has_wifi: true,
    has_outlets: true,
    is_24_7: false,
    is_free: false,
    needs_student_id: false,
    comp_shop_reg_required: false,
    indoor_outdoor: 'both',
    seat_capacity: 'Moderate',
    commute_info: {
      lrt: 'LRT-1 Central Terminal Station (8 min walk)',
      jeep: 'Intramuros / Pier 15 jeepneys',
    },
    peak_hours: '12 PM - 5 PM',
    cover_image_url: imgBreaktimeBrew,
  },

  // --- LIBRARIES ---
  {
    id: 'spot-nlp',
    university_id: 'uni-upm',
    title: 'National Library of the Philippines',
    category: 'library',
    description: 'The premier public library of the country located on Kalaw Ave. Offers vast research collections, air-conditioned reading rooms, and free public access.',
    address: 'T.M. Kalaw Ave, Ermita, Manila',
    lat: 14.58205,
    lng: 120.98104,
    price_range: 'Free',
    has_wifi: true,
    has_outlets: true,
    is_24_7: false,
    is_free: true,
    needs_student_id: true,
    comp_shop_reg_required: false,
    indoor_outdoor: 'indoor',
    seat_capacity: 'Very Spacious',
    commute_info: {
      lrt: 'LRT-1 United Nations (UN) Station (5 min walk)',
      jeep: 'Kalaw - Taft route',
    },
    peak_hours: '9 AM - 4 PM',
    cover_image_url: imgNatlib,
  },
  {
    id: 'spot-mcl-main',
    university_id: 'uni-cghc',
    title: 'Manila City Library - Main (Lacson/Aragon)',
    category: 'library',
    description: 'The main public municipal library building located at Lacson Ave corner Aragon St near CGHC. Features extensive historical Manila archives and quiet study tables.',
    address: 'Lacson Ave cor. Aragon St, Sampaloc, Manila',
    lat: 14.6100,
    lng: 120.9890,
    price_range: 'Free',
    has_wifi: true,
    has_outlets: true,
    is_24_7: false,
    is_free: true,
    needs_student_id: false,
    comp_shop_reg_required: false,
    indoor_outdoor: 'indoor',
    seat_capacity: 'Spacious',
    commute_info: {
      lrt: 'LRT-1 Tayuman Station (8 min walk)',
    },
    peak_hours: '1 PM - 4 PM',
    cover_image_url: imgManilaLibMain,
  },
  {
    id: 'spot-mcl-annex',
    university_id: 'uni-upm',
    title: 'Manila City Library - Annex (Taft)',
    category: 'library',
    description: 'A convenient public library branch located along Taft Ave near UN. Quiet atmosphere suitable for self-study and thesis drafting.',
    address: 'Taft Ave, Ermita, Manila',
    lat: 14.5750,
    lng: 120.9850,
    price_range: 'Free',
    has_wifi: true,
    has_outlets: true,
    is_24_7: false,
    is_free: true,
    needs_student_id: false,
    comp_shop_reg_required: false,
    indoor_outdoor: 'indoor',
    seat_capacity: 'Moderate',
    commute_info: {
      lrt: 'LRT-1 UN Avenue Station (3 min walk)',
    },
    peak_hours: '10 AM - 3 PM',
    cover_image_url: imgManilaLibTaft,
  },
  {
    id: 'spot-jpl-library',
    university_id: 'uni-upm',
    title: "Jose P. Laurel Memorial Foundation Library & Museum",
    category: 'library',
    description: 'A serene heritage library and museum located along Roxas Boulevard corner Pedro Gil St. Offers a unique historical backdrop for quiet reading.',
    address: 'Roxas Blvd cor. Pedro Gil St, Manila',
    lat: 14.5732,
    lng: 120.9820,
    price_range: 'Free',
    has_wifi: false,
    has_outlets: true,
    is_24_7: false,
    is_free: true,
    needs_student_id: true,
    comp_shop_reg_required: false,
    indoor_outdoor: 'indoor',
    seat_capacity: 'Quiet & Intimate',
    commute_info: {
      jeep: 'Pedro Gil - Roxas Blvd route',
    },
    peak_hours: '10 AM - 2 PM',
    cover_image_url: imgJplLib,
  },
  {
    id: 'spot-magsaysay-library',
    university_id: 'uni-upm',
    title: "Ramon Magsaysay Center - Laureate Library",
    category: 'library',
    description: 'Specialized Asian laureate library housed in the iconic Ramon Magsaysay Center. Access facilities require a small donation fee.',
    address: 'Roxas Blvd cor. Quintos St, Malate, Manila',
    lat: 14.5719,
    lng: 120.9822,
    price_range: '₱ (Donation)',
    has_wifi: true,
    has_outlets: true,
    is_24_7: false,
    is_free: false,
    needs_student_id: true,
    comp_shop_reg_required: false,
    indoor_outdoor: 'indoor',
    seat_capacity: 'Moderate',
    commute_info: {
      jeep: 'Mabini / Roxas Blvd jeepneys',
    },
    peak_hours: '11 AM - 3 PM',
    cover_image_url: imgMagsaysayLib,
  },
  {
    id: 'spot-centro-turismo',
    university_id: 'uni-plm',
    title: 'Centro de Turismo Intramuros Library (Museo de Intramuros)',
    category: 'library',
    description: 'A modern research library located inside Museo de Intramuros. Student entrance fee is ₱120 which includes full access to museum galleries!',
    address: 'Museo de Intramuros, Arzobispo St, Intramuros, Manila',
    lat: 14.5890,
    lng: 120.9750,
    price_range: '₱120',
    has_wifi: true,
    has_outlets: true,
    is_24_7: false,
    is_free: false,
    needs_student_id: true,
    comp_shop_reg_required: false,
    indoor_outdoor: 'indoor',
    seat_capacity: 'Moderate',
    commute_info: {
      lrt: 'LRT-1 Central Terminal Station (10 min walk)',
    },
    peak_hours: '1 PM - 4 PM',
    cover_image_url: imgCentroTurismoLib,
  },

  // --- PARKS ---
  {
    id: 'spot-rizal-park',
    university_id: 'uni-upm',
    title: 'Rizal Park / Luneta Park',
    category: 'park',
    description: 'Manila iconic historic urban park featuring shaded gardens, outdoor benches, open green lawns, and fresh air for outdoor reading.',
    address: 'Roxas Blvd, Ermita, Manila',
    lat: 14.58250,
    lng: 120.97833,
    price_range: 'Free',
    has_wifi: false,
    has_outlets: false,
    is_24_7: true,
    is_free: true,
    needs_student_id: false,
    comp_shop_reg_required: false,
    indoor_outdoor: 'outdoor',
    seat_capacity: 'Very Spacious',
    commute_info: {
      lrt: 'LRT-1 UN Avenue Station (5 min walk)',
    },
    peak_hours: '4 PM - 7 PM',
    cover_image_url: imgRizalPark,
  },
  {
    id: 'spot-arroceros',
    university_id: 'uni-plm',
    title: 'Arroceros Forest Park',
    category: 'park',
    description: "Known as 'Manila's Last Pink Lung', a lush 2.2-hectare urban forest park filled with trees, quiet pathways, and fresh air right beside the Pasig River.",
    address: 'Antonio Villegas St, Ermita, Manila',
    lat: 14.5942,
    lng: 120.9818,
    price_range: 'Free',
    has_wifi: false,
    has_outlets: false,
    is_24_7: false,
    is_free: true,
    needs_student_id: false,
    comp_shop_reg_required: false,
    indoor_outdoor: 'outdoor',
    seat_capacity: 'Spacious',
    commute_info: {
      lrt: 'LRT-1 Central Terminal Station (1 min walk)',
    },
    peak_hours: '8 AM - 11 AM',
    cover_image_url: imgArrocerosPark,
  },
  {
    id: 'spot-paco-park',
    university_id: 'uni-upm',
    title: 'Paco Park & Garden',
    category: 'park',
    description: 'A peaceful, circular historic park enclosed by stone walls in Paco. Very tranquil for reading books or taking study breaks.',
    address: 'San Marcelino St, Paco, Manila',
    lat: 14.58122,
    lng: 120.98889,
    price_range: 'Free',
    has_wifi: false,
    has_outlets: false,
    is_24_7: false,
    is_free: true,
    needs_student_id: false,
    comp_shop_reg_required: false,
    indoor_outdoor: 'outdoor',
    seat_capacity: 'Moderate',
    commute_info: {
      lrt: 'LRT-1 Pedro Gil Station (10 min walk)',
      jeep: 'Paco - Faura jeepneys',
    },
    peak_hours: '3 PM - 6 PM',
    cover_image_url: imgPacoPark,
  },

  // --- STUDY HUBS ---
  {
    id: 'spot-homeroom-dapitan',
    university_id: 'uni-ust',
    title: 'HomeRoom Co-Working & Study Lounge',
    category: 'coworking',
    description: 'A top student favorite located at 1521 Dapitan St near UST & U-Belt. Offers high-speed fiber internet, ergonomic chairs, power sockets at every desk, and unlimited coffee.',
    address: '1521 Dapitan St, Sampaloc, Manila',
    lat: 14.6105,
    lng: 120.9890,
    price_range: '₱₱',
    has_wifi: true,
    has_outlets: true,
    is_24_7: true,
    is_free: false,
    needs_student_id: false,
    comp_shop_reg_required: false,
    indoor_outdoor: 'indoor',
    seat_capacity: 'Spacious',
    commute_info: {
      jeep: 'Dapitan - Quiapo route',
    },
    peak_hours: '1 PM - 11 PM',
    cover_image_url: imgHomeRoom,
  },
  {
    id: 'spot-933-coworking',
    university_id: 'uni-ust',
    title: '933 Coworking Cafe (Sampaloc)',
    category: 'coworking',
    description: 'Popular multi-story student study hub at 854 Tolentino St in Sampaloc. Features soundproof booth pods, fast internet, and affordable hourly rates.',
    address: '854 Tolentino St, Sampaloc, Manila',
    lat: 14.6040,
    lng: 120.9850,
    price_range: '₱₱',
    has_wifi: true,
    has_outlets: true,
    is_24_7: true,
    is_free: false,
    needs_student_id: false,
    comp_shop_reg_required: false,
    indoor_outdoor: 'indoor',
    seat_capacity: 'Spacious',
    commute_info: {
      jeep: 'España Blvd jeepneys',
    },
    peak_hours: '2 PM - 2 AM',
    cover_image_url: img933Coworking,
  },
  {
    id: 'spot-hashlab-study',
    university_id: 'uni-feu',
    title: 'Hash Lab Budget Study Cafe',
    category: 'coworking',
    description: 'Budget-friendly study lounge in Sampaloc serving U-Belt students (FEU, UE, UST). Extremely affordable hourly pass with fast Wi-Fi.',
    address: 'P. Noval St, Sampaloc, Manila',
    lat: 14.605936,
    lng: 120.987238,
    price_range: '₱',
    has_wifi: true,
    has_outlets: true,
    is_24_7: true,
    is_free: false,
    needs_student_id: false,
    comp_shop_reg_required: false,
    indoor_outdoor: 'indoor',
    seat_capacity: 'Moderate',
    commute_info: {
      jeep: 'Gastambide / Morayta jeepneys',
    },
    peak_hours: '1 PM - 10 PM',
    cover_image_url: imgHashLab,
  },
  {
    id: 'spot-cloudscape-hub',
    university_id: 'uni-dlsu',
    title: "Cloudscape Study Hub (Vito Cruz)",
    category: 'coworking',
    description: 'Modern 24/7 study sanctuary located at D’Students Place in Vito Cruz near DLSU & CSB. Super fast fiber connection and private desk dividers.',
    address: "D'Students Place, Vito Cruz, Malate, Manila",
    lat: 14.5630,
    lng: 120.9940,
    price_range: '₱₱',
    has_wifi: true,
    has_outlets: true,
    is_24_7: true,
    is_free: false,
    needs_student_id: false,
    comp_shop_reg_required: false,
    indoor_outdoor: 'indoor',
    seat_capacity: 'Spacious',
    commute_info: {
      lrt: 'LRT-1 Vito Cruz Station (2 min walk)',
    },
    peak_hours: '12 PM - 3 AM',
    cover_image_url: imgCloudscape,
  },
];
